version: '3'
services:
  php:
    build: ./docker/php
    volumes:
      - ./:/app

  database:
    image: mariadb
    volumes:
      - ./structure.sql:/docker-entrypoint-initdb.d/structure.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: php_telegram_bot
      MYSQL_USER: php_telegram_bot
      MYSQL_PASSWORD: php_telegram_bot
